spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
        url: jdbc:postgresql://localhost:5432/engel_volkers?stringtype=unspecified
    jpa:
        properties:
            hibernate:
                types:
                    print:
                        banner: false  
        database-platform: org.hibernate.dialect.PostgreSQL9Dialect
        generate-ddl: false
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            ddl-auto: validate
        show-sql: true
    jackson:
        default-property-inclusion: NON_NULL
    liquibase:
        enabled: true
        drop-first: false
        change-log: classpath:db/liquibase-changelog.xml
        default-schema: public
logging:
    level:
        org:
            hibernate:
                type: trace